feat: custom instruction and hint UI
ocadotechnology/rapid-router pull request #1646
Opened 2024-06-10 15:23 UTC by evemartin

2024-06-18 10:32 UTC, faucomte97 requested changes
> Reviewed 2 of 15 files at r1, 5 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: 7 of 16 files reviewed, 12 unresolved discussions (waiting on @evemartin)

___
*[`game/messages.py` line 104 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-elwEQ99hDl9CWxtF5:-O-elwEQ99hDl9CWxtF6:b-38nkqj) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L104)):*
> ```Python
> 
> 
> def title_level_default():
> ```

This isn't used anywhere - please remove (I know you didn't work on this but it ties in closely with what this PR is doing)
___
*[`game/messages.py` line 108 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-em1x85gtN_8e6fZit:-O-em1x91fTwmQAsETI-:bbqrs6n) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L108)):*
> ```Python
> 
> 
> def description_level_default():
> ```

This is the default `description/lesson` text, if you specify it in `models` you should be able to remove it from here. Be mindful of where this current function is being used though.
___
*[`game/messages.py` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-emCtQ-MJ17Ktberwo:-O-emCtQ-MJ17Ktberwp:b-o0bd8o) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L112)):*
> ```Python
> 
> 
> def subtitle_level_default():
> ```

If `subtitle` can be null/blank then I don't think we should need this.
___
*[`game/messages.py` line 116 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-emAVV2XLyY5-31rHk:-O-emAVV2XLyY5-31rHl:b7fmknf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L116)):*
> ```Python
> 
> 
> def hint_level_default():
> ```

This is the default `hint` text, if you specify it in `models` you should be able to remove it from here. Be mindful of where this current function is being used though.
___
*[`game/models.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-ejACnBBauq4xMKfn9:-O-ejACnBBauq4xMKfnA:b-vosun3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L159)):*
> ```Python
>         max_length=20, choices=character_choices(), blank=True, null=True, default=None
>     )
>     subtitle = models.TextField(max_length=10000, null=True)
> ```

You can reduce the length of this, for a subtitle I reckon you can make it 100 chars max.
___
*[`game/models.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-el32c9ulLx9rFfCtQ:-O-el32c9ulLx9rFfCtR:bfm50nh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L159)):*
> ```Python
>         max_length=20, choices=character_choices(), blank=True, null=True, default=None
>     )
>     subtitle = models.TextField(max_length=10000, null=True)
> ```

Add `blank=True`
___
*[`game/models.py` line 160 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-elAZ30QHUakBfkl90:-O-elAZ30QHUakBfkl91:b-g5cofc) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L160)):*
> ```Python
>     )
>     subtitle = models.TextField(max_length=10000, null=True)
>     lesson = models.TextField(max_length=10000, null=True)
> ```

It seems like we'll have a default `lesson` if the user doesn't enter one. As such, please remove `null=True`, and add a `default` equal to our default `lesson` text.
___
*[`game/models.py` line 161 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-elMwL0wSwHfN2mpmb:-O-ejJum5y8ri2GNgABm:b-pc82iw) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L161)):*
> ```Python
>     subtitle = models.TextField(max_length=10000, null=True)
>     lesson = models.TextField(max_length=10000, null=True)
>     hint = models.TextField(max_length=10000, null=True)
> ```

It seems like we'll have a default `hint` if the user doesn't enter one. As such, please remove `null=True`, and add a `default` equal to our default `hint` text.
___
*[`game/static/game/js/animation.js` line 353 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-enJVb3UXMqrwwZYoF:-O-enJVb3UXMqrwwZYoG:byp18fd) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/static/game/js/animation.js#L353)):*
> ```JavaScript
> 			var otherMsg = "";
> 			if (animation.popupHint) {
> 				console.log("popuphint");
> ```

Remove
___
*[`game/static/game/js/animation.js` line 357 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-enLKY3zGadoUp_UsD:-O-enLKY3zGadoUp_UsE:byp18fd) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/static/game/js/animation.js#L357)):*
> ```JavaScript
> 				otherMsg = '<div id="hintBtnPara">' + '</div><div id="hintText">' + HINT + '</div>';
> 			}
> 			console.log(buttons);
> ```

Remove
___
*[`game/static/game/js/level_editor.js` line 194 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-enZCB5UxN4OjeeW5A:-O-enZCB5UxN4OjeeW5B:b-91qvig) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/static/game/js/level_editor.js#L194)):*
> ```JavaScript
>         tabs.blocks = new ocargo.Tab($('#blocks_radio'), $('#blocks_radio + label'), $('#blocks_pane'));
>         tabs.random = new ocargo.Tab($('#random_radio'), $('#random_radio + label'), $('#random_pane'));
>         tabs.instruction = new ocargo.Tab($('#instruction_radio'), $('#instruction_radio + label'), $('#instruction_pane'));
> ```

After checking with Laura, we should rename this to `tabs.description`
___
*[`game/templates/game/level_editor.html` line 508 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-etv706Su1UuHxPoJ9:-O-etv706Su1UuHxPoJA:b-jfhro2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/templates/game/level_editor.html#L508)):*
> ```HTML
>                 <textarea id="instruction" rows="4" cols="50"></textarea>
>               </div>
>             </div>
> ```

There seems to be an issue with this section not showing up (same problem in hint pane).

Pausing my review so you can have a look.



_Code quote:_
```HTML
            <div class="tab_pane_content_holder">
              <div class="tab_pane_content">
                <p>{% trans "<b>Subtitle</b><br>What is the subtitle of this level?" %}</p>
                <textarea id="subtitle" rows="4" cols="50"></textarea>

                <p>{% trans "<b>Instruction</b><br>What do players have to do to complete this level?" %}</p>
                <textarea id="instruction" rows="4" cols="50"></textarea>
              </div>
            </div>
```


<!-- Sent from Reviewable.io -->

2024-06-19 09:02 UTC, faucomte97 requested changes
> Reviewed 1 of 15 files at r1, 4 of 13 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: all files reviewed, 19 unresolved discussions (waiting on @evemartin)

___
*[`game/end_to_end_tests/test_level_editor.py` line 5 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jiBL80q8obBO2W64w:-O-jiBL90N-5ZKrPB4CE:b-ismepq) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/end_to_end_tests/test_level_editor.py#L5)):*
> ```Python
> from selenium.webdriver.support import expected_conditions as EC
> from selenium.webdriver.support.ui import Select
> from selenium.webdriver.support.ui import WebDriverWait
> ```

Combine these imports pls



_Code quote:_
```Python
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
```
___
*[`game/end_to_end_tests/test_level_editor.py` line 199 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jijtB0LQ_Aqj8HDIw:-O-jijtB0LQ_Aqj8HDIx:bgrzs1b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/end_to_end_tests/test_level_editor.py#L199)):*
> ```Python
>             EC.visibility_of_element_located((By.ID, "myModal-mainText"))
>         )
>         hint_modal_text_three = self.selenium.find_element(By.ID, "myModal-mainText").get_attribute("innerHTML")
> ```

Why `three`? :sweat_smile: 
___
*[`game/end_to_end_tests/test_level_editor.py` line 201 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jimX5-r6dtPRBp5dQ:-O-jimX5-r6dtPRBp5dR:b-5nuasr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/end_to_end_tests/test_level_editor.py#L201)):*
> ```Python
>         hint_modal_text_three = self.selenium.find_element(By.ID, "myModal-mainText").get_attribute("innerHTML")
>         assert "test hint" in hint_modal_text_three
>         
> ```

Blank spaces - run Black
___
*[`game/static/game/image/icons/instruction.svg` line 0 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jiwmYADfWNU4aFAxH:-O-jiwmYADfWNU4aFAxI:bt5q5pm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/static/game/image/icons/instruction.svg#L0)):*
Rename to description.svg
___
*[`game/static/game/js/game.js` line 10 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jgIdp9gHnEWJW6JSE:-O-jgIdp9gHnEWJW6JSF:b-zeymiu) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/static/game/js/game.js#L10)):*
> ```JavaScript
>   this.currentlySelectedTab = null
>   this.isMuted = Cookies.get('muted') === 'true'
>   this.hasTimedHintAppeared = false
> ```

No need for this as we're no longer doing timed hints for now
___
*[`game/static/game/js/game.js` line 289 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jgQNM6KvySU1T8FIE:-O-jgQNM6KvySU1T8FIF:b-r2alhe) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/static/game/js/game.js#L289)):*
> ```JavaScript
> ocargo.Game.prototype.registerFailure = function () {
>   this.failures += 1
>   return this.failures >= 1
> ```

Any idea why this was a 3 before, and how come you changed it to 1?
___
*[`game/static/game/js/level_editor.js` line 194 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-enZCB5UxN4OjeeW5A:-O-jgW7c4YEbnnwW80IM:b-kawbxh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/static/game/js/level_editor.js#L194)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

After checking with Laura, we should rename this to `tabs.description`
</blockquote></details>

(along with every other instance, sorry :grimacing:)
___
*[`game/templates/game/level_editor.html` line 202 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jgjc81fzETIYsoUhO:-O-jgjc81fzETIYsoUhP:b-kmlah5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/templates/game/level_editor.html#L202)):*
> ```HTML
>           <label for="instruction_radio">
>             <img src='{% static "game/image/icons/instruction.svg" %}'>
>             <span>{% trans "Instruction" %}</span>
> ```

Description
___
*[`game/templates/game/level_editor.html` line 511 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jh1x37IGHTxguAk2I:-O-jh1x37IGHTxguAk2J:bvmgffh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/templates/game/level_editor.html#L511)):*
> ```HTML
> 
>                 <p>{% trans "<b>Instruction</b><br>What do players have to do to complete this level?" %}</p>
>                 <textarea id="instruction" rows="4" cols="50"></textarea>
> ```

There's no save button after this (check with Laura)


<!-- Sent from Reviewable.io -->

2024-06-20 10:37 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: 3 of 19 files reviewed, 19 unresolved discussions (waiting on @faucomte97)

___
*[`game/messages.py` line 104 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-elwEQ99hDl9CWxtF5:-O-lEoU0C11L_0kT0uH8:b-896fja) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L104)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This isn't used anywhere - please remove (I know you didn't work on this but it ties in closely with what this PR is doing)
</blockquote></details>

Done!
___
*[`game/messages.py` line 108 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-em1x85gtN_8e6fZit:-O-p1aq3CHG5IIYGdcvt:bss4a1y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L108)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This is the default `description/lesson` text, if you specify it in `models` you should be able to remove it from here. Be mindful of where this current function is being used though.
</blockquote></details>

Removed!
___
*[`game/messages.py` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-emCtQ-MJ17Ktberwo:-O-p1c-u6HDJsOLpJ941:bss4a1y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L112)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

If `subtitle` can be null/blank then I don't think we should need this.
</blockquote></details>

Removed!
___
*[`game/messages.py` line 116 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-emAVV2XLyY5-31rHk:-O-p1d3HBf_Cxfndy_WQ:bss4a1y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/messages.py#L116)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This is the default `hint` text, if you specify it in `models` you should be able to remove it from here. Be mindful of where this current function is being used though.
</blockquote></details>

Removed!
___
*[`game/models.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-ejACnBBauq4xMKfn9:-O-lF3g80BV07_tuO_yT:b-896fja) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L159)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You can reduce the length of this, for a subtitle I reckon you can make it 100 chars max.
</blockquote></details>

Done!
___
*[`game/models.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-el32c9ulLx9rFfCtQ:-O-lF4I58f5-HICycGhU:b-896fja) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L159)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Add `blank=True`
</blockquote></details>

Done!
___
*[`game/models.py` line 160 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-elAZ30QHUakBfkl90:-O-p78dG4FFpkQIYou27:b-bw8e1h) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L160)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

It seems like we'll have a default `lesson` if the user doesn't enter one. As such, please remove `null=True`, and add a `default` equal to our default `lesson` text.
</blockquote></details>

Updated!
___
*[`game/models.py` line 161 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-elMwL0wSwHfN2mpmb:-O-p79Y_6gCtno3r7mQn:b-bw8e1h) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L161)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

It seems like we'll have a default `hint` if the user doesn't enter one. As such, please remove `null=True`, and add a `default` equal to our default `hint` text.
</blockquote></details>

Updated!
___
*[`game/end_to_end_tests/test_level_editor.py` line 5 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jiBL80q8obBO2W64w:-O-lFBlj4dwwd6B7ZA_G:b-896fja) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/end_to_end_tests/test_level_editor.py#L5)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Combine these imports pls
</blockquote></details>

Done!
___
*[`game/end_to_end_tests/test_level_editor.py` line 199 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jijtB0LQ_Aqj8HDIw:-O-lFIf_6sC4x7Qx8bhT:b4wx2hy) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/end_to_end_tests/test_level_editor.py#L199)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why `three`? :sweat_smile:
</blockquote></details>

I used to have another check to do with the hint modal text but when we got rid of the timer/trigger we didn't need that one anymore, I just forgot to rename :sweat_smile: Fixed!
___
*[`game/end_to_end_tests/test_level_editor.py` line 201 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jimX5-r6dtPRBp5dQ:-O-lLyXHDoOLfm38EsUJ:besgv62) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/end_to_end_tests/test_level_editor.py#L201)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Blank spaces - run Black
</blockquote></details>

Formatted!
___
*[`game/static/game/js/animation.js` line 353 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-enJVb3UXMqrwwZYoF:-O-or8fL8Dyzzcu7Vno4:bss4a1y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/static/game/js/animation.js#L353)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Removed!
___
*[`game/static/game/js/animation.js` line 357 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-enLKY3zGadoUp_UsD:-O-orA2v66qGwlABMas3:bss4a1y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/static/game/js/animation.js#L357)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Removed!
___
*[`game/static/game/js/game.js` line 10 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jgIdp9gHnEWJW6JSE:-O-or3Qx7ceDZ1dOuPNp:bss4a1y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/static/game/js/game.js#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

No need for this as we're no longer doing timed hints for now
</blockquote></details>

Removed!
___
*[`game/static/game/js/game.js` line 289 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jgQNM6KvySU1T8FIE:-O-oqYDX0GJugELRml28:bs5t3hr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/static/game/js/game.js#L289)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Any idea why this was a 3 before, and how come yo [...]

2024-06-21 11:00 UTC, faucomte97 requested changes
> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: all files reviewed, 6 unresolved discussions (waiting on @evemartin)

___
*[`game/models.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-el32c9ulLx9rFfCtQ:-O-uPe8N98w9zKFShTk8:b39yedj) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L159)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

Done!
</blockquote></details>

Ah, but we can leave `null=True`, right?
___
*[`game/serializers.py` line 86 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uQBM09ef7pD1kgvRt:-O-uQBM09ef7pD1kgvRu:bbdhqbc) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/serializers.py#L86)):*
> ```Python
>             return description
>         else:
>             return "Can you find the shortest route?"
> ```

I have a feeling that we no longer need this in this way. Essentially, this piece of code checks if the level is a "default" level (ie, not custom) and if so, it gets the description from the large file with all the descriptions & titles. If not, it used to return the default description from that same file.

Now that we've moved the default description string to the model, we can probably do something like this:

`return getattr(messages, "description_level" + obj.name)() if obj.default else obj.description`

Let me know if that makes sense. If so, try it out and see if it works.

This is still not an ideal solution, ideally all the descriptions, hints, titles and subtitles would now be saved directly on the model level and not loaded from a file. But for now, this will do.
___
*[`game/serializers.py` line 93 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uR7HV8JCw7dy1uq3r:-O-uR7HV8JCw7dy1uq3s:b-iguvzs) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/serializers.py#L93)):*
> ```Python
>             return hint
>         else:
>             return "Think back to earlier levels. What did you learn?"
> ```

Same logic as above.
___
*[`game/static/game/js/game.js` line 289 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-jgQNM6KvySU1T8FIE:-O-uRklv7Z3xtIXSU1bR:bcsyaih) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/490e75ffe510789d6daa1d793dd49762deddf555/game/static/game/js/game.js#L289)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

I think it was a 3 before so that the hint prompt only appeared on the failure modal after the player had made a few attempts - Stefan, Laura, and I discussed hint behavior on Friday and the conclusion we came to was that the prompt should appear on every failure modal since players can technically access the hint at any time via the level toolbar but that we would check in with teachers about hint prompting to see if this works for them!
</blockquote></details>

Oh I see, that's cool!
___
*[`game/static/game/js/level_editor/owned_levels.js` line 45 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uRsPJBbfb6_bfWSY3:-O-uRsPJBbfb6_bfWSY4:b-v6tfsq) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/static/game/js/level_editor/owned_levels.js#L45)):*
> ```JavaScript
>         delete level.name;
> 
>         console.log(level);
> ```

Remove :)
___
*[`game/templates/game/level_editor.html` line 503 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uRw8l7lIRwO4GPtbn:-O-uRw8l7lIRwO4GPtbo:b-wdrk5g) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/templates/game/level_editor.html#L503)):*
> ```HTML
>           <div id="description_pane" class="tab_pane">
>             <h2 class="title"><img class="modal_image" src='{% static "game/image/icons/description.svg" %}'>{% trans "Description" %}</h2>
>             <p> {% trans "Give this level a subtitle and a description describing what to do within this level for your students." %} </p>
> ```

wording is a bit redundant - I think "Give this level a subtitle and a description of what to do within this level for your students" is OK
___
*[`game/migrations/0094_add_description_hint__subtitle_to_levels.py` line 26 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uRVhJ2aBlaais9XwW:-O-uRVhJ2aBlaais9XwX:bnrumnz) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/migrations/0094_add_description_hint__subtitle_to_levels.py#L26)):*
> ```Python
>             model_name='level',
>             name='subtitle',
>             field=models.TextField(default='', max_length=10000),
> ```

The max_length here is still 10000, I think you may need to re-make the migration.


<!-- Sent from Reviewable.io -->

2024-06-24 12:53 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: 15 of 19 files reviewed, 6 unresolved discussions (waiting on @faucomte97)

___
*[`game/models.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-el32c9ulLx9rFfCtQ:-O09FKAIBMw27EVwM4Ez:b-is9hzc) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L159)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Ah, but we can leave `null=True`, right?
</blockquote></details>

If I omit `null=True` then an empty subtitle is saved and later printed as an empty string, whereas if I include it then it's saved as the value `NULL` and printed as the value `None` - I could provide the empty string as a default value but I think it will be cleaner to just leave out `null=True`!
___
*[`game/serializers.py` line 86 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uQBM09ef7pD1kgvRt:-O09GTNZ6oiN84tcBkEF:bjyq99b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/serializers.py#L86)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I have a feeling that we no longer need this in this way. Essentially, this piece of code checks if the level is a "default" level (ie, not custom) and if so, it gets the description from the large file with all the descriptions & titles. If not, it used to return the default description from that same file.

Now that we've moved the default description string to the model, we can probably do something like this:

`return getattr(messages, "description_level" + obj.name)() if obj.default else obj.description`

Let me know if that makes sense. If so, try it out and see if it works.

This is still not an ideal solution, ideally all the descriptions, hints, titles and subtitles would now be saved directly on the model level and not loaded from a file. But for now, this will do.
</blockquote></details>

That does make sense! I have tested it out and it seems to work :) 
___
*[`game/serializers.py` line 93 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uR7HV8JCw7dy1uq3r:-O09I_xH50xJwwfdNRFs:b-o6m6z2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/serializers.py#L93)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same logic as above.
</blockquote></details>

Same fix as above!
___
*[`game/templates/game/level_editor.html` line 503 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uRw8l7lIRwO4GPtbn:-O09G55o5QAgRHXEdWT-:b-896fja) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/templates/game/level_editor.html#L503)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

wording is a bit redundant - I think "Give this level a subtitle and a description of what to do within this level for your students" is OK
</blockquote></details>

Done!
___
*[`game/static/game/js/level_editor/owned_levels.js` line 45 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uRsPJBbfb6_bfWSY3:-O09G6A81RfZDLioIOrw:b-896fja) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/static/game/js/level_editor/owned_levels.js#L45)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove :)
</blockquote></details>

Done!
___
*[`game/migrations/0094_add_description_hint__subtitle_to_levels.py` line 26 at r4](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-uRVhJ2aBlaais9XwW:-O09FrYvE1dCZ4sLOId7:bql6ur0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/c2a58b5a40c2d32d681d31ad86fcca0872d30efe/game/migrations/0094_add_description_hint__subtitle_to_levels.py#L26)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The max_length here is still 10000, I think you may need to re-make the migration.
</blockquote></details>

Should be fixed now!


<!-- Sent from Reviewable.io -->

2024-06-24 14:27 UTC, faucomte97 requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: all files reviewed, 1 unresolved discussion (waiting on @evemartin)

___
*[`game/models.py` line 159 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O-el32c9ulLx9rFfCtQ:-O09cz2k-rB1rWO1zZO2:b9n0r9h) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/003f97b052cb69aea9f3ec4997aa6f1e7178b2b7/game/models.py#L159)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

If I omit `null=True` then an empty subtitle is saved and later printed as an empty string, whereas if I include it then it's saved as the value `NULL` and printed as the value `None` - I could provide the empty string as a default value but I think it will be cleaner to just leave out `null=True`!
</blockquote></details>

Where does it get printed as `None`? If the value of `subtitle` is `None` then it shouldn't get used / printed anywhere - if we ensure that's the case then maybe we can have `null=True`.
But if that's not really doable then I agree with what you're saying :slightly_smiling_face: 


<!-- Sent from Reviewable.io -->

2024-06-24 15:22 UTC, faucomte97 requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: all files reviewed, 2 unresolved discussions (waiting on @evemartin)

___
*[`game/static/game/js/drawing.js` line 1045 at r6](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O09pjZSAqeDe_e1JUpD:-O09pjZSAqeDe_e1JUpE:b-17mssf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/045cd22a283fb4b835393cbfe0cfa5a741b9c7b1/game/static/game/js/drawing.js#L1045)):*
> ```JavaScript
>   buttons
> ) {
>   console.log(subtitle)
> ```

Remove :stuck_out_tongue: 
___
*[`game/static/game/js/level_editor.js` line 2632 at r6](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O09ppa1AH5GJ_u2djUI:-O09ppa1AH5GJ_u2djUJ:b-x7jokr) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/045cd22a283fb4b835393cbfe0cfa5a741b9c7b1/game/static/game/js/level_editor.js#L2632)):*
> ```JavaScript
>                 if(blocks[i].number) {
>                     $('#' + type + '_number').val(blocks[i].number);
>                 }restoreState
> ```

is this a mistake copy paste? :thinking: 


<!-- Sent from Reviewable.io -->

2024-06-24 15:25 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`game/static/game/js/drawing.js` line 1045 at r6](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O09pjZSAqeDe_e1JUpD:-O09qP-x1EwaSxbbpfWE:bl7he2i) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/045cd22a283fb4b835393cbfe0cfa5a741b9c7b1/game/static/game/js/drawing.js#L1045)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove :stuck_out_tongue:
</blockquote></details>

I'm so sorry for this, removed :sweat: 
___
*[`game/static/game/js/level_editor.js` line 2632 at r6](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-O09ppa1AH5GJ_u2djUI:-O09qRkO9b5BnbxcmUZ5:bd6asy5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/045cd22a283fb4b835393cbfe0cfa5a741b9c7b1/game/static/game/js/level_editor.js#L2632)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

is this a mistake copy paste? :thinking:
</blockquote></details>

Yes it is, also removed :sweat_smile: 


<!-- Sent from Reviewable.io -->

2024-06-24 15:25 UTC, faucomte97 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1646#-:-O09qXhx4tYZOITrSUx-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)



<!-- Sent from Reviewable.io -->

2024-06-24 15:32 UTC, merged

2024-07-01 16:07 UTC, evemartin commented
Update before I go on holiday: on production, I have made a new ticket (linked on the other task) to address the emoji bug