feat: build python den levels
ocadotechnology/rapid-router pull request #1696
Opened 2024-08-06 16:10 UTC by evemartin

2024-08-12 15:33 UTC, faucomte97 requested changes
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 2 of 9 files reviewed, 7 unresolved discussions (waiting on @evemartin)

___
*[`game/messages.py` line 2480 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O462bYZAqI12a-jYRAW:-O462bYZAqI12a-jYRAX:bipf00n) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/messages.py#L2480)):*
> ```Python
>     return (
>         "To decrease the value of a variable by an amount you can do something like the "
>         "following:<br><pre>number = number - 5</pre>" + PYTHON_HINT
> ```

Are we using `count` or `number`?
___
*[`game/messages.py` line 3657 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46AYKY1AcC3YztAG4Y:-O46AYKY1AcC3YztAG4Z:b-yrsh89) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/messages.py#L3657)):*
> ```Python
>         24: "Lists",
>         25: "For Loops",
>         26: "Procedures"
> ```

Episodes 12-15 are duplicated by 20-22 and 25. Let's reuse them instead if possible



_Code quote:_
```Python
        12: "Counted Loops Using While",
        13: "Indeterminate While Loops - coming soon",
        14: "Selection in a Loop - coming soon",
        15: "For Loops - coming soon",
        16: "Output, Operators, and Data",
        17: "Variables, Input, and Casting",
        18: "Selection",
        19: "Complex Selection",
        20: "Counted Loops Using While",
        21: "Selection in a Loop",
        22: "Indeterminate Loops",
        23: "String Manipulation",
        24: "Lists",
        25: "For Loops",
        26: "Procedures"
```
___
*[`game/end_to_end_tests/test_play_through.py` line 282 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46AgheBd-ywJX1xFG-:-O46AgheBd-ywJX1xFG0:bi5wk2t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/end_to_end_tests/test_play_through.py#L282)):*
> ```Python
>     def test_episode_20(self):
>         self._complete_episode(20, 1001, check_algorithm_score=False)
>     
> ```

run Black
___
*[`game/migrations/0097_add_python_den_levels.py` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46ArL88u-Z2z2yRVIY:-O46ArL88u-Z2z2yRVIZ:b-4dghv3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L14)):*
> ```Python
>     episode21 = Episode.objects.get(pk=21)
>     episode22 = Episode.objects.get(pk=22)
>     episode25 = Episode.objects.get(pk=25)
> ```

These 4 episodes are basically episodes 12-15. See if you can reuse the already existing ones instead of creating new ones. Therefore same goes for the levels inside of episode 12.



_Code quote:_
```Python
    episode20 = Episode.objects.get(pk=20)
    episode21 = Episode.objects.get(pk=21)
    episode22 = Episode.objects.get(pk=22)
    episode25 = Episode.objects.get(pk=25)
```
___
*[`game/migrations/0097_add_python_den_levels.py` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46B67JBUB9B7TC56e1:-O46B67JBUB9B7TC56e2:bo6nvhh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L17)):*
> ```Python
>     episode26 = Episode.objects.get(pk=26)
> 
>     level1 = Level.objects.get(name="110", default=True)
> ```

I think it would be nicer if we kept the name of the variable to the name we give the level, so in this case, `level110`.
___
*[`game/migrations/0097_add_python_den_levels.py` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46BFuK6zWoVRa0nqhM:-O46BFuK6zWoVRa0nqhN:b6k673t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L20)):*
> ```Python
>     level1.pk = None
>     level1._state.adding = True
>     level1.name = "1001"
> ```

Why are you renaming it?
___
*[`game/migrations/0097_add_python_den_levels.py` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46BHtY0H1RdEvr1OJS:-O46BHtY0H1RdEvr1OJT:b-87u06b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L21)):*
> ```Python
>     level1._state.adding = True
>     level1.name = "1001"
>     level1.episode = episode20
> ```

No need to change the episode it's in if you just reuse the episode we already have.


<!-- Sent from Reviewable.io -->

2024-08-12 18:04 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @faucomte97)

___
*[`game/messages.py` line 2480 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O462bYZAqI12a-jYRAW:-O46Gqco4Zlhlfods6Ft:b-omysay) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/messages.py#L2480)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Are we using `count` or `number`?
</blockquote></details>

Originally this was `count` but this was actually a change specifically requested by Rebecca - I am not 100% sure of her reasoning 
![image.png](https://files.reviewableusercontent.io/images/reviewable/162978916/VyFAsv-YLO6MdVw7meQdNSA_/image.png)
___
*[`game/messages.py` line 3657 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46AYKY1AcC3YztAG4Y:-O46I7tJ-RU--irLMphW:b-nqvjna) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/messages.py#L3657)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Episodes 12-15 are duplicated by 20-22 and 25. Let's reuse them instead if possible
</blockquote></details>

Episode list has been updated :)
___
*[`game/end_to_end_tests/test_play_through.py` line 282 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46AgheBd-ywJX1xFG-:-O46kmWy4xrIld-Ho7pc:bau9rzv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/end_to_end_tests/test_play_through.py#L282)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

run Black
</blockquote></details>

I have now run it!
___
*[`game/migrations/0097_add_python_den_levels.py` line 14 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46ArL88u-Z2z2yRVIY:-O46L-WJ2nDooYSA3qlX:b-p73nh4) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

These 4 episodes are basically episodes 12-15. See if you can reuse the already existing ones instead of creating new ones. Therefore same goes for the levels inside of episode 12.
</blockquote></details>

Should be adjusted now!
___
*[`game/migrations/0097_add_python_den_levels.py` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46B67JBUB9B7TC56e1:-O46LNVw62QyHyyPxVen:bj2v0ft) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L17)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I think it would be nicer if we kept the name of the variable to the name we give the level, so in this case, `level110`.
</blockquote></details>

I agree, but I think it would be nicer to give these levels the names they'll have in Python Den, so in this case it would be `level1001` (except not for this level specifically because it is no longer renamed)
___
*[`game/migrations/0097_add_python_den_levels.py` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46BFuK6zWoVRa0nqhM:-O46L2fo1hHDEc59xXrQ:bmpimbw) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L20)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why are you renaming it?
</blockquote></details>

Since the name is used in the URL, I needed to give the Python Den levels names that didn't match any Rapid Router levels - but since I'm no longer duplicating these levels they won't need to be renamed anymore!
___
*[`game/migrations/0097_add_python_den_levels.py` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O46BHtY0H1RdEvr1OJS:-O46LkqA9VHGdPUB8Fr7:b-kfosnc) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/migrations/0097_add_python_den_levels.py#L21)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

No need to change the episode it's in if you just reuse the episode we already have.
</blockquote></details>

Should be fixed now too!


<!-- Sent from Reviewable.io -->

2024-08-12 18:15 UTC, evemartin commented
Note: finalizing the final levels and next levels/episodes will happen as part of the levels page task, since in this task the levels aren't actually being prepared for display yet, they're just being built. That means that as part of the next task, in addition to setting final levels and double checking next levels/episodes, some tests will have to be updated

2024-08-13 14:44 UTC, faucomte97 requested changes
> Reviewed 3 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: all files reviewed, 13 unresolved discussions (waiting on @evemartin)

___
*[`game/messages.py` line 2480 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O462bYZAqI12a-jYRAW:-O4APnyMBC8FK0uVs7NL:basd4gt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/messages.py#L2480)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

Originally this was `count` but this was actually a change specifically requested by Rebecca - I am not 100% sure of her reasoning 
![image.png](https://files.reviewableusercontent.io/images/reviewable/162978916/VyFAsv-YLO6MdVw7meQdNSA_/image.png)
</blockquote></details>

Hmm. I'm asking mainly because I saw that you updated `number` to `count` in level 106, so I'm not sure this is consistent. Would you mind double checking with Rebecca? :pray: 
___
*[`game/messages.py` line 2707 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BBPg3BtEQQhVctdsW:-O4BBPg3BtEQQhVctdsX:b-c00kao) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/messages.py#L2707)):*
> ```Python
>     title_level123,
>     description_level123,
>     hint_level123,
> ```

Following Ridwanah's work we can now specify which commands are relevant in Python-only levels - please ensure only the commands that are strictly needed to complete the level are linked to the new Python levels you've created, like level 122 above.
___
*[`game/migrations/0097_add_python_den_levels.py` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4ATTX-E6FGBk5Q8IOl:-O4ATTX-E6FGBk5Q8IOm:b57dsj1) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L26)):*
> ```Python
>         default=True,
>         destinations="[[9,4]]",
>         disable_algorithm_score=True,
> ```

Enable algorithm score for all Blockly & Python levels pls.
Basically any level that has a non-empty `model_solution` should have the algo score enabled.
___
*[`game/migrations/0097_add_python_den_levels.py` line 318 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B5WBW-920PuSGSLX5:-O4B5WBW-920PuSGSLX6:b-9pi23b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L318)):*
> ```Python
>     )
> 
>     level1026 = Level.objects.get(name="85", default=True)
> ```

Similarly to the episodes, do we need to create new level objects for the levels we already have? We'll just be able to reference them in the levels page, right?

This goes for all levels that copy previous ones.
___
*[`game/migrations/0097_add_python_den_levels.py` line 450 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B7FGz0IA8WlF93LOy:-O4B7FGz0IA8WlF93LOz:b-ixwyvz) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L450)):*
> ```Python
>         pythonEnabled=True,
>         pythonViewEnabled=False,
>         theme_name="grass",
> ```

Seems like the theme is snow on dev?
___
*[`game/migrations/0097_add_python_den_levels.py` line 453 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B6oxn-IoBvxQmHFT8:-O4B6oxn-IoBvxQmHFT9:b-y6g7at) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L453)):*
> ```Python
>         character_name="Van",
>         lesson="Can you find the shortest route?",
>         hint="In this level, you want to check for a left turn first. If there is no left turn, turn right. Notice what that looks like in Python.",
> ```

That last sentence is weird for students in the context of a hint.
___
*[`game/migrations/0097_add_python_den_levels.py` line 1169 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ac7_B4zpW0y-YRLKJ:-O4Ac7_B4zpW0y-YRLKK:bu52l0e) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L1169)):*
> ```Python
>         )
>     )
> ```

You're missing the decor for level 1019
___
*[`game/migrations/0097_add_python_den_levels.py` line 1374 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAhQV9lD8wrcCD1ax:-O4BAhQV9lD8wrcCD1ay:brszpz0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L1374)):*
> ```Python
>     Episode = apps.get_model("game", "Episode")
>     Level = apps.get_model("game", "Level")
>     
> ```

Run Black!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1414 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAGNk3pNRygKpp54m:-O4BAGNk3pNRygKpp54n:buusm1v) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L1414)):*
> ```Python
>         migrations.RunPython(code=add_python_den_decor),
>         migrations.RunPython(code=set_first_and_last_levels)
>     ]
> ```

I know this is gonna be a pain.

But for each of these operations, since they are custom code, can you please add the equivalent reverse code for each of them, in case we ever need to reverse the migration?

It should be easier than creating the levels really.

In theory, you should just need to delete the new levels, blocks and decors you've created, then undo the next_episode and last_level changes etc.



_Code quote:_
```Python
    operations = [
        migrations.RunPython(code=delete_old_loop_levels),
        migrations.RunPython(code=create_python_den_episodes),
        migrations.RunPython(code=add_python_den_levels),
        migrations.RunPython(code=add_python_den_blocks),
        migrations.RunPython(code=add_python_den_decor),
        migrations.RunPython(code=set_first_and_last_levels)
    ]
```
___
*[`game/static/game/js/game.js` line 117 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAl7m-jskuRfqfBzZ:-O4BAl7m-jskuRfqfBz_:b-ure48r) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/static/game/js/game.js#L117)):*
> ```JavaScript
>     }
> 
>     var adjusted_level_name = ''
> ```

make this a `let` if possible
___
*[`game/static/game/js/skulpt/skulpt-stdlib.js` line 0 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Aasb96kej9PmYd2tH:-O4AasbABZCnkoyf55Tq:b-ft4uzv) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/static/game/js/skulpt/skulpt-stdlib.js#L0)):*
As I was testing the levels locally I realised that the Python lines to `increment` (maybe just when a Python only level) do not get highlighted.
___
*[`game/templates/game/level_selection.html` line 190 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAwzk5mL8XwdJK8cr:-O4BAwzk5mL8XwdJK8cs:bgqxqfm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d6ca990cd13e7ed6285c4cca08954bb4c5605488/game/templates/game/level_selection.html#L190)):*
> ```HTML
>                         <p class="episode-title" data-toggle="collapse" data-target="#collapse-{{episode.id}}" aria-expanded="false" aria-controls="collapse-{{episode.id}}" data-parent="#episodes">
>                             {{episode.name}}
>                             <span class="episode_range_text collapsed" data-toggle="collapse" data-target="#collapse-{{episode.id}}" aria-expanded="false" aria-controls=" [...]

2024-08-13 20:16 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 3 of 10 files reviewed, 13 unresolved discussions (waiting on @faucomte97)

___
*[`game/messages.py` line 2480 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O462bYZAqI12a-jYRAW:-O4BETPoAZ_rm0R4iqfG:b5hdh1t) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/messages.py#L2480)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Hmm. I'm asking mainly because I saw that you updated `number` to `count` in level 106, so I'm not sure this is consistent. Would you mind double checking with Rebecca? :pray:
</blockquote></details>

Can do! I'll ping her about it in the document :thumbsup: 
___
*[`game/messages.py` line 2707 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BBPg3BtEQQhVctdsW:-O4BosW90ynEYY9_tCD2:b-t06eow) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/messages.py#L2707)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Following Ridwanah's work we can now specify which commands are relevant in Python-only levels - please ensure only the commands that are strictly needed to complete the level are linked to the new Python levels you've created, like level 122 above.
</blockquote></details>

Should be added now!
___
*[`game/migrations/0097_add_python_den_levels.py` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4ATTX-E6FGBk5Q8IOl:-O4BIG0h3ycmBRrdSBSO:bql6ur0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L26)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Enable algorithm score for all Blockly & Python levels pls.
Basically any level that has a non-empty `model_solution` should have the algo score enabled.
</blockquote></details>

Should be fixed now!
___
*[`game/migrations/0097_add_python_den_levels.py` line 318 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B5WBW-920PuSGSLX5:-O4BCt6ABhhpJDcdmPDx:b-8pqmn) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L318)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Similarly to the episodes, do we need to create new level objects for the levels we already have? We'll just be able to reference them in the levels page, right?

This goes for all levels that copy previous ones.
</blockquote></details>

I originally just referenced existing levels but because they get added to Python Den in a different order I needed to change the `next_level` values for them when they got moved, which caused some issues with the original levels. Since we need to maintain the original level order for now I think it still makes sense to duplicate levels when the order is affected - that said if I'm missing something please let me know!!
___
*[`game/migrations/0097_add_python_den_levels.py` line 450 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B7FGz0IA8WlF93LOy:-O4BISh71s7GVN8pWJ54:bt2vr0y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L450)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Seems like the theme is snow on dev?
</blockquote></details>

Fixed!
___
*[`game/migrations/0097_add_python_den_levels.py` line 453 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B6oxn-IoBvxQmHFT8:-O4BG-jmBzuloNLd8X6o:bas11y2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L453)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

That last sentence is weird for students in the context of a hint.
</blockquote></details>

It is a bit weird, but it is what Rebecca has put on dev - I'll ping her to double check!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1169 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ac7_B4zpW0y-YRLKJ:-O4BHQb56Ds04rT5GOuQ:bqmjwcm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L1169)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You're missing the decor for level 1019
</blockquote></details>

Added!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1374 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAhQV9lD8wrcCD1ax:-O4C3Tfm5hkelDjUvs8b:brqdmzf) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L1374)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Run Black!
</blockquote></details>

Should now have run it!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1414 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAGNk3pNRygKpp54m:-O4BItVKD4pmD9kRKc3m:b-cyz7kt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L1414)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I know this is gonna be a pain.

But for each of these operations, since they are custom code, can you please add the equivalent reverse code for each of them, in case we ever need to reverse the migration?

It should be easier than creating the levels really.

In theory, you should just need to delete the new levels, blocks and decors you've created, then undo the next_episode and last_level changes etc.
</blockquote></details>

Should be done now! I ended up copying over the code to recreate the old loop levels from an older migration (0086) because it was actually only a small part of that code
___
*[`game/static/game/js/game.js` line 117 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAl7m-jskuRfqfBzZ:-O4BFl2a0O6WFtsV61Ql:bt2vr0y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/static/game/js/game.js#L117)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

make this a `let` if possible
</blockquote></details>

Fixed!
___
*[`game/static/game/js/skulpt/skulpt-stdlib.js` line  at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Aasb96kej9PmYd2tH:-O4BIVa707mnEnaAMh0B:bl6aq4e) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/static/game/js/skulpt/skulpt-stdlib.js#L)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

As I was testing the levels locally I realised that the Python lines to `increment` (maybe just when a Python only level) do not get highlighted.
</blockquote></details>

Ah I've just gone to look and found the same - it looks like procedures also highlight strangely in that they don't highlight the line where the procedure is called, they only highlight the code within the procedure. This is definitely worth investigating but I'm not 100% sure it's within the scope of this task, maybe we can create a new task to look at the highlighting?
___
*[`game/templates/game/level_selection.html` line 190 at r2](https://reviewable.io/reviews/ocadotechnology/ [...]

2024-08-14 11:45 UTC, faucomte97 requested changes
> Reviewed 2 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 5 of 10 files reviewed, 4 unresolved discussions (waiting on @evemartin)

___
*[`game/migrations/0097_add_python_den_levels.py` line 26 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4ATTX-E6FGBk5Q8IOl:-O4Ff8OkCbL7oJ9uogrY:b-g23px6) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L26)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

Should be fixed now!
</blockquote></details>

Reminder to myself to discuss this with you in a call
___
*[`game/migrations/0097_add_python_den_levels.py` line 318 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B5WBW-920PuSGSLX5:-O4FfpXs-rrpE9_QfhBS:b-g23px6) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L318)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

I originally just referenced existing levels but because they get added to Python Den in a different order I needed to change the `next_level` values for them when they got moved, which caused some issues with the original levels. Since we need to maintain the original level order for now I think it still makes sense to duplicate levels when the order is affected - that said if I'm missing something please let me know!!
</blockquote></details>

Reminder to myself to discuss this with you in a call
___
*[`game/static/game/js/skulpt/skulpt-stdlib.js` line  at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Aasb96kej9PmYd2tH:-O4FgdH-6G9NnCvONr1Z:b-ucdj9k) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/static/game/js/skulpt/skulpt-stdlib.js#L)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

Ah I've just gone to look and found the same - it looks like procedures also highlight strangely in that they don't highlight the line where the procedure is called, they only highlight the code within the procedure. This is definitely worth investigating but I'm not 100% sure it's within the scope of this task, maybe we can create a new task to look at the highlighting?
</blockquote></details>

Yes, that sounds good.
___
*[`game/templates/game/level_selection.html` line 190 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAwzk5mL8XwdJK8cr:-O4FgsjH0KPJLy3TRyUw:bjh5xez) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d6ca990cd13e7ed6285c4cca08954bb4c5605488/game/templates/game/level_selection.html#L190)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

The existing "coming soon" episodes now have Python Den levels associated with them but the Python Den levels are named differently, so on the existing Rapid Router page these episodes were showing up as having levels 1014-1026 etc - I thought I would remove this bit so that it wasn't confusing but I could also just change what is displayed?
</blockquote></details>

Ah I see, that makes sense!


<!-- Sent from Reviewable.io -->

2024-08-14 11:49 UTC, faucomte97 requested changes
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @evemartin)

___
*[`game/templates/game/level_selection.html` line 192 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4FhwOQAe34WhDCF1VR:-O4FhwOQAe34WhDCF1VS:b-mtrsju) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d6ca990cd13e7ed6285c4cca08954bb4c5605488/game/templates/game/level_selection.html#L192)):*
> ```HTML
>                             <span class="episode_range_text collapsed" data-toggle="collapse" data-target="#collapse-{{episode.id}}" aria-expanded="false" aria-controls="collapse-{{episode.id}}" data-parent="#episodes">
>                                 Levels {{episode.first_level}}-{{episode.last_level}}
>                             </span>
> ```

Actually I just realised, removing this causes the dropdown arrow on the side to disappear as well, and it removes the level numbers for the first While loop episode that is already out.

I suggest instead, you bring this `span` back but you remove the 3 "coming soon" episodes from the list altogether. No point in having them on the page anymore.



_Code quote:_
```HTML
                            <span class="episode_range_text collapsed" data-toggle="collapse" data-target="#collapse-{{episode.id}}" aria-expanded="false" aria-controls="collapse-{{episode.id}}" data-parent="#episodes">
                                Levels {{episode.first_level}}-{{episode.last_level}}
                            </span>
```


<!-- Sent from Reviewable.io -->

2024-08-14 12:33 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`game/templates/game/level_selection.html` line 192 at r3](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4FhwOQAe34WhDCF1VR:-O4FjykO06ZtpCMVDhQd:b-1jn5ej) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d6ca990cd13e7ed6285c4cca08954bb4c5605488/game/templates/game/level_selection.html#L192)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Actually I just realised, removing this causes the dropdown arrow on the side to disappear as well, and it removes the level numbers for the first While loop episode that is already out.

I suggest instead, you bring this `span` back but you remove the 3 "coming soon" episodes from the list altogether. No point in having them on the page anymore.
</blockquote></details>

Oooo thank you for pointing this out! I have implemented this now :thumbsup:


<!-- Sent from Reviewable.io -->

2024-08-14 12:35 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`game/messages.py` line 2480 at r1](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O462bYZAqI12a-jYRAW:-O4FsM17Big7a3w242Be:b-wjl717) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/b86327bd27d1eee86b2bad641deaa2f5e3c63a81/game/messages.py#L2480)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

Can do! I'll ping her about it in the document :thumbsup:
</blockquote></details>

She confirmed that changing it to count would make more sense, I have fixed this now :) 
___
*[`game/migrations/0097_add_python_den_levels.py` line 453 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B6oxn-IoBvxQmHFT8:-O4FsPSE59KWt-VlWIjI:b-6df3pm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L453)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

It is a bit weird, but it is what Rebecca has put on dev - I'll ping her to double check!
</blockquote></details>

It looks like Rebecca has confirmed that it should be the hint?
![image.png](https://files.reviewableusercontent.io/images/reviewable/162978916/ntjGgoFeCm7HROyv45ekj-gh/image.png)
___
*[`game/static/game/js/skulpt/skulpt-stdlib.js` line  at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Aasb96kej9PmYd2tH:-O4FsUmm4mzpuO0CooXo:b-hp05ot) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/static/game/js/skulpt/skulpt-stdlib.js#L)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Yes, that sounds good.
</blockquote></details>

I have made a task for this now: https://app.zenhub.com/workspaces/code-for-life-sprint-board-5dc58d4a85c6bd00010b8148/issues/gh/ocadotechnology/rapid-router/1703
___
*[`game/templates/game/level_selection.html` line 190 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4BAwzk5mL8XwdJK8cr:-O4FsZVb83D73av2zBvL:bth58tp) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/d6ca990cd13e7ed6285c4cca08954bb4c5605488/game/templates/game/level_selection.html#L190)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Ah I see, that makes sense!
</blockquote></details>

Addressed with the implementation you suggested in another comment :) 


<!-- Sent from Reviewable.io -->

2024-08-14 16:27 UTC, faucomte97 requested changes
> Reviewed 3 of 7 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: all files reviewed, 14 unresolved discussions (waiting on @evemartin)

___
*[`game/messages.py` line 3124 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ga1Nc3UYmMzfsqbgw:-O4Ga1Nc3UYmMzfsqbgx:bonhp6b) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3124)):*
> ```Python
>     + "<br>my_van.turn_left()"
>     + "<br>my_van.turn_right()"
>     + "<br>my_van.sound_horn()</div>"
> ```

"sound horn" falls under the "Animals" section (see default commands text in the Level model)
___
*[`game/messages.py` line 3126 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4G_nRK2bh11dstjKwR:-O4G_nRK2bh11dstjKwS:b-uzbapl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3126)):*
> ```Python
>     + "<br>my_van.sound_horn()</div>"
>     + '<div class="large-4 columns">'
>     + "<br>my_van.is_animal_crossing()</div>"
> ```

You're missing the "Animals" header here
___
*[`game/messages.py` line 3144 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GaH1LBDrggPMfU5Z0:-O4GaH1LBDrggPMfU5Z1:b61vnlp) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3144)):*
> ```Python
>     + '<div class="large-4 columns">'
>     + "<b>Position</b>"
>     + "<br>my_van.is_road_forward()</div>"
> ```

The solution doesn't use `is_road_forward`, but `is_road_left`
___
*[`game/messages.py` line 3410 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GcchV1fpyt2g1jmqU:-O4GcchV1fpyt2g1jmqV:b-9897xx) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3410)):*
> ```Python
>     + "<br>my_van.turn_around()"
>     + "<br>my_van.turn_right()"
>     + "<br>my_van.sound_horn()</div>"
> ```

Same here, sound horn and is animal crossing belong under the Animals category
___
*[`game/messages.py` line 3429 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Gcp9G3K-0c9Vk2cT8:-O4Gcp9G3K-0c9Vk2cT9:buo9nmt) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3429)):*
> ```Python
>     + "<br>my_van.move_forwards()"
>     + "<br>my_van.turn_left()"
>     + "<br>my_van.sound_horn()</div>"
> ```

Same here
___
*[`game/messages.py` line 3442 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GdFb83Mj4ri-dZjja:-O4GdFb83Mj4ri-dZjjb:b-s1wim1) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3442)):*
> ```Python
>     lambda: description_level48(),
>     lambda: hint_level48(),
>     lambda: '<div class="row">'
> ```

These commands here didn't get saved for some reason, seems like it's still loading the ones from the old level.
___
*[`game/migrations/0097_add_python_den_levels.py` line 318 at r2](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4B5WBW-920PuSGSLX5:-O4G1puO9is4UScOliPs:bpjtkvo) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/fc995df74a57eef30980445ad033fb935ce1cb84/game/migrations/0097_add_python_den_levels.py#L318)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Reminder to myself to discuss this with you in a call
</blockquote></details>

Fix `bulk_decor_copy` args order
Make note to delete old levels when we do the transition
___
*[`game/migrations/0097_add_python_den_levels.py` line 642 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ggy7Y0bTOa74N0O_y:-O4Ggy7Y0bTOa74N0O_z:b-6i3oy0) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L642)):*
> ```Python
>     for i in range(1014, 1061):
>         deleted_level = Level.objects.get(name=i, default=True)
>         deleted_level.delete()
> ```

Do this instead:

`Level.objects.filter(name__in=range(1014, 1061)).delete()`



_Code quote:_
```Python
    for i in range(1014, 1061):
        deleted_level = Level.objects.get(name=i, default=True)
        deleted_level.delete()
```
___
*[`game/migrations/0097_add_python_den_levels.py` line 935 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GfTO16mQqjHQYeDkJ:-O4GfTO24U6u5XbOMbVF:bgr48sm) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L935)):*
> ```Python
>         deleted_level_blocks = LevelBlock.objects.filter(level_id=i)
>         for block in deleted_level_blocks:
>             block.delete()
> ```

Here, just do `LevelBlock.objects.filter(level_id=i).delete()`



_Code quote:_
```Python
        deleted_level_blocks = LevelBlock.objects.filter(level_id=i)
        for block in deleted_level_blocks:
            block.delete()
```
___
*[`game/migrations/0097_add_python_den_levels.py` line 1205 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GfgzFEFo1H4vD58WR:-O4GfgzFEFo1H4vD58WS:b-499f81) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1205)):*
> ```Python
>         deleted_level_decor = LevelDecor.objects.filter(level_id=i)
>         for decor_element in deleted_level_decor:
>             decor_element.delete()
> ```

Same here, you can just do `LevelDecor.objects.filter(level_id=i).delete()`



_Code quote:_
```Python
        deleted_level_decor = LevelDecor.objects.filter(level_id=i)
        for decor_element in deleted_level_decor:
            decor_element.delete()
```
___
*[`game/migrations/0097_add_python_den_levels.py` line 1259 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Gh96P-XEtGulqcMS3:-O4Gh96P-XEtGulqcMS4:b-uvagj5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1259)):*
> ```Python
>     episode20.next_episode = episode21
>     episode21.next_episode = episode15
>     episode15.next_episode = episode22
> ```

You're not saving the episodes here?
___
*[`game/migrations/0097_add_python_den_levels.py` line 1266 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ggr1wDcIStFP8MprK:-O4Ggr1wDcIStFP8MprL:bth7j7f) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1266)):*
> ```Python
>     for i in range(16, 23):
>         deleted_episode = Episode.objects.get(pk=i)
>         deleted_episode.delete()
> ```

Do this instead:

`Episode.objects.filter(pk__in=range(16, 23)).delete()`



_Code quote:_
```Python
    for i in range(16, 23):
        deleted_episode = Episode.objects.get(pk=i)
        deleted_episode.delete()
```
___
*[`game/migrations/0097_add_python_den_levels.py` line 1271 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GhBX6DFwYd11Db-ln:-O4GhBX6DFwYd11Db-lo:b-uvagj5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1271)):*
> ```Python
>     episode15 = Episode.objects.get(pk=15)
>     episode14.next_episode = episode15
>     episode15.next_episode = None
> ```

You're not saving the episodes here?
___
*[`game/migrations/0097_add_python_den_levels.py` line 1280 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GhM4j77ErSQZkpxOC:-O4GhM4j77ErSQZkpxOD:b-m3c51i) ([raw file](https://gi [...]

2024-08-14 17:23 UTC, evemartin reviewed
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: 9 of 11 files reviewed, 14 unresolved discussions (waiting on @faucomte97)

___
*[`game/messages.py` line 3124 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ga1Nc3UYmMzfsqbgw:-O4GkrmM4atzuN0jOOxn:bqgv0hi) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3124)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

"sound horn" falls under the "Animals" section (see default commands text in the Level model)
</blockquote></details>

Added! Sorry, I skimmed over the commands text too quickly
___
*[`game/messages.py` line 3126 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4G_nRK2bh11dstjKwR:-O4GkvGY5jjhr8h0dYIi:bo9hi5m) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3126)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You're missing the "Animals" header here
</blockquote></details>

Added as well!
___
*[`game/messages.py` line 3144 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GaH1LBDrggPMfU5Z0:-O4GlONU9bc6-cHoY_D3:bt2vr0y) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3144)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The solution doesn't use `is_road_forward`, but `is_road_left`
</blockquote></details>

Fixed!
___
*[`game/messages.py` line 3410 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GcchV1fpyt2g1jmqU:-O4GlOuz-lOIxMFdf1rB:b-g6notk) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3410)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here, sound horn and is animal crossing belong under the Animals category
</blockquote></details>

Added here too!
___
*[`game/messages.py` line 3429 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Gcp9G3K-0c9Vk2cT8:-O4GlZA2BbGoKlWoLkhd:bcixqot) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3429)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Also added here!
___
*[`game/messages.py` line 3442 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GdFb83Mj4ri-dZjja:-O4GlfIv4CM9WIF83VEu:b-lt1gxh) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/messages.py#L3442)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

These commands here didn't get saved for some reason, seems like it's still loading the ones from the old level.
</blockquote></details>

It looks like I had a typo with `commands_level40` instead of `commands_level1040`, should be fixed now!
___
*[`game/migrations/0097_add_python_den_levels.py` line 642 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ggy7Y0bTOa74N0O_y:-O4GnbY86acVHtIK1UXr:b-m4mdi3) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L642)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do this instead:

`Level.objects.filter(name__in=range(1014, 1061)).delete()`
</blockquote></details>

Thank you for this, changed now!!
___
*[`game/migrations/0097_add_python_den_levels.py` line 935 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GfTO16mQqjHQYeDkJ:-O4Go3aF2lv0mlLWW4ez:b81xj99) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L935)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Here, just do `LevelBlock.objects.filter(level_id=i).delete()`
</blockquote></details>

Changed! I have used `level_id__in` as in the previous comment
___
*[`game/migrations/0097_add_python_den_levels.py` line 1205 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GfgzFEFo1H4vD58WR:-O4Go8wVEV0bM636n2fC:b5zpsf5) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1205)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here, you can just do `LevelDecor.objects.filter(level_id=i).delete()`
</blockquote></details>

Also changed!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1259 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Gh96P-XEtGulqcMS3:-O4GosKt2fndpfuMELmk:b-gxn1ls) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1259)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You're not saving the episodes here?
</blockquote></details>

Ah thank you for pointing this out, they should be saved now!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1266 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4Ggr1wDcIStFP8MprK:-O4GophE7iFLLCeqWIRx:b-a2ujfy) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1266)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do this instead:

`Episode.objects.filter(pk__in=range(16, 23)).delete()`
</blockquote></details>

Changed!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1271 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GhBX6DFwYd11Db-ln:-O4Gp5Rg9sCstOqa7ghJ:bnrmepl) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1271)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You're not saving the episodes here?
</blockquote></details>

Should be saved now!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1280 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GhM4j77ErSQZkpxOC:-O4GpF3N7aqDegUcWRfx:b-bw8e1h) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1280)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

No need to create a variable for these if they're just used on the next line. Combine the two (same goes for the lines below)
</blockquote></details>

Updated!
___
*[`game/migrations/0097_add_python_den_levels.py` line 1323 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GhiXr9-hWh48Er3cz:-O4GpMS1EIw_I6XyH_nL:bjrb7p2) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L1323)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

`Level.objects.filter(name__in=range(123, 154)).delete()`
</blockquote></details>

Changed as well!


<!-- Sent from Reviewable.io -->

2024-08-14 21:10 UTC, faucomte97 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-:-O4Hi_aN0bCUA3BGXpfw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)

___
*[`game/migrations/0097_add_python_den_levels.py` line 935 at r5](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696#-O4GfTO16mQqjHQYeDkJ:-O4HiLFg0NvRA1fmepHP:b9flqkw) ([raw file](https://github.com/ocadotechnology/rapid-router/blob/f645c1025942c5ed8141b07fd4889ef6f2da5451/game/migrations/0097_add_python_den_levels.py#L935)):*
<details><summary><i>Previously, evemartin wrote…</i></summary><blockquote>

Changed! I have used `level_id__in` as in the previous comment
</blockquote></details>

Even better!


<!-- Sent from Reviewable.io -->

2024-08-15 12:49 UTC, faucomte97 approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/rapid-router/1696)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @evemartin)



<!-- Sent from Reviewable.io -->

2024-08-15 12:50 UTC, merged